import type { IFieldConfig } from './iFormFieldConfig';


export const BOT_FORM_CONFIG: IFieldConfig[] = [
    {
        name: 'BOT_ID',
        label: 'Идентификатор чат-бота',
        type: 'select',
        required: true,
        invalidFeedback: 'Укажите идентификатор бота',
        createForm: false,
        editForm: true,
        options: null,
    },
    {
        name: 'CODE',
        label: 'Строковой идентификатор бота, уникальный в рамках приложения',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите идентификатор бота',
        createForm: true,
        editForm: true,
    },
    {
        name: 'TYPE',
        label: 'Тип чат-бота',
        type: 'select',
        required: true,
        invalidFeedback: 'Укажите тип бота',
        createForm: true,
        editForm: false,
        options: [
            { value: 'O', label: 'Чат-бот для Открытых линий' },
            { value: 'B', label: 'Чат-бот, ответы поступают сразу'},
            { value: 'S', label: 'Чат-бот с повышенными привилегиями'}
        ],
    },
    {
        name: 'EVENT_HANDLER',
        label: 'Ссылка на обработчик события отправки сообщения чат-боту',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите ссылку',
        createForm: true,
        editForm: true,
    },
    {
        name: 'EVENT_WELCOME_MESSAGE',
        label: 'Ссылка на обработчик события открытия диалога с чат-ботом или приглашения его в групповой чат',
        type: 'text',
        required: false,
        invalidFeedback: 'Укажите ссылку',
        createForm: true,
        editForm: true,
    },
    {
        name: 'EVENT_BOT_DELETE',
        label: 'Ссылка на обработчик события удаления чат-бота со стороны клиента',
        type: 'text',
        required: false,
        invalidFeedback: 'Укажите ссылку',
        createForm: true,
        editForm: true,
    },
    {
        name: 'OPENLINE',
        label: 'Включение режима поддержки Открытых линий',
        type: 'select',
        required: true,
        invalidFeedback: 'Укажите режим',
        createForm: true,
        editForm: false,
        options: [
            { value: 'Y', label: 'Да' },
            { value: 'N', label: 'Нет'},
        ],
    },
    {
        name: 'CLIENT_ID',
        label: 'Строковый идентификатор клиента',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите строковый идентификатор клиента',
        createForm: true,
        editForm: true,
    },
    {
        name: 'PROPERTIES__NAME',
        label: 'Имя чат-бота',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите имя бота',
        createForm: true,
        editForm: true,
    },
    {
        name: 'PROPERTIES__LAST_NAME',
        label: 'Фамилия чат-бота',
        type: 'text',
        required: false,
        invalidFeedback: 'Укажите фамилию бота',
        createForm: true,
        editForm: true,
    },
    {
        name: 'PROPERTIES__COLOR',
        label: 'Цвет для мобильного приложения',
        type: 'select',
        required: false,
        invalidFeedback: 'Укажите цвет',
        createForm: true,
        editForm: true,
        options: [
            { value: 'RED', label: 'Красный' },
            { value: 'GREEN', label: 'Зеленый' },
            { value: 'MINT', label: 'Мятный' },
            { value: 'LIGHT_BLUE', label: 'Голубой' },
            { value: 'DARK_BLUE', label: 'Темно-синий' },
            { value: 'PURPLE', label: 'Фиолетовый' },
            { value: 'AQUA', label: 'Аквамариновый' },
            { value: 'PINK', label: 'Розовый' },
            { value: 'LIME', label: 'Лаймовый' },
            { value: 'BROWN', label: 'Коричневый' },
            { value: 'AZURE', label: 'Лазурный' },
            { value: 'KHAKI', label: 'Хаки' },
            { value: 'SAND', label: 'Песочный' },
            { value: 'MARENGO', label: 'Маренго' },
            { value: 'GRAY', label: 'Серый' },
            { value: 'GRAPHITE', label: 'Графитовый' },
        ],
    },
    {
        name: 'PROPERTIES__PERSONAL_PHOTO',
        label: 'Аватар',
        type: 'file',
        required: false,
        invalidFeedback: 'Укажите аватар',
        createForm: true,
        editForm: true,
    },
]
