import type { IFieldConfig } from './iFormFieldConfig';


export const COMMAND_FORM_CONFIG: IFieldConfig[] = [
    {
        name: 'COMMAND_ID',
        label: 'Идентификатор команды',
        type: 'number',
        required: true,
        invalidFeedback: 'Укажите идентификатор команды',
        createForm: false,
        editForm: true,
    },
    {
        name: 'BOT_ID',
        label: 'Идентификатор чат-бота владельца команды',
        type: 'select',
        required: true,
        invalidFeedback: 'Укажите идентификатор бота',
        createForm: true,
        editForm: false,
        options: null,
    },
    {
        name: 'COMMAND',
        label: 'Текст команды, которую пользователь будет вводить в чатах',
        type: 'text',
        required: true,
        invalidFeedback: 'Можно использовать только латинские буквы и цифры. Не принимает пробелы и спецсимволы',
        createForm: true,
        editForm: false,
    },
    {
        name: 'COMMON',
        label: 'Доступность команды',
        type: 'select',
        required: true,
        invalidFeedback: 'Укажите доступность команды',
        createForm: true,
        editForm: false,
        options: [
            { value: 'Y', label: 'Доступна во всех чатах' },
            { value: 'N', label: 'Доступна только в тех чатах, где присутствует чат-бот'},
        ],
    },
    {
        name: 'HIDDEN',
        label: 'Скрытая команда или нет',
        type: 'select',
        required: true,
        invalidFeedback: 'Укажите тип команды',
        createForm: true,
        editForm: true,
        options: [
            { value: 'Y', label: 'Скрытая команда' },
            { value: 'N', label: 'Открытая команда'},
        ],
    },
    {
        name: 'CLIENT_ID',
        label: 'Строковый идентификатор чат-бота, используется только в режиме Вебхуков',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите идентификатор чат-бота',
        createForm: true,
        editForm: true,
    },
    {
        name: 'LANG__RU',
        label: 'Расшифровка команды на русском',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите расшифровку',
        createForm: true,
        editForm: true,
    },
    {
        name: 'LANG__EN',
        label: 'Расшифровка команды на английском',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите расшифровку',
        createForm: true,
        editForm: true,
    },
    {
        name: 'EVENT_COMMAND_ADD',
        label: 'Ссылка на обработчик для команд',
        type: 'text',
        required: true,
        invalidFeedback: 'Укажите ссылку',
        createForm: true,
        editForm: true,
    },
];
